### PR TITLE
Use the pipenv instead of requirements.txt

### LINKED ISSUE #2: Use the pipenv instead of requirements.txt
It would be nice to manage dependencies via pipenv instead of requirements.txt files. The reason is that you have automatic virtualenv management, deterministic install/uninstall of dependencies and so on.
https://docs.pipenv.org/

(... I thing this is a package or library: "Structural geology `module` for Python". ?)

### PR DESCRIPTION
**Pull request by uetoyo**
This closes #2

### CODE REVIEW

**Comment by uetoyo** [comment]
Hello Ondrej, I know there is more then `use pipenv` in this pull request and I apologize for this.
I want to work on this project, so instruct me what should be done... BTW: I'm beginner in the field of structural geology. Happy new year!

**Comment by ondrolexa** [comment]
Hi David,
thanks for your interest in my project. I see no trouble to use pipfile instead requirements.txt, but there is a problem with the commit to define version inside the package and use it in setup.py.  Command `from apsg import __version__, __author__, __email__` will fail for a fresh install as apsg is not yet available. I prefer to have version number in setup.py and if needed get it with `pkg_resources.get_distribution('apsg').version`

**Comment by ondrolexa** [comment]
Please submit your pull requests separately so I can merge it. Thanks.

**Comment by ondrolexa** [comment]
Hi David,
thanks for your input. I merged your pull request to develop branch.

**Pull request closed without merging**
