### PR TITLE
Change the project structure and drop Python 2 support

### PR DESCRIPTION
**Pull request by uetoyo**
__Changes__

- [x] The source code is placed in the `src` folder. 
  - https://hynek.me/articles/testing-packaging/
  - https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure
  - https://github.com/pypa/packaging.python.org/issues/320

- [x] Black source code formatter is included in `setup.py` and applied with `--skip-string-normalization` flag.
- [ ] The support for Python 2 is dropped and some new features of Python 3 included.

### CODE REVIEW

**Comment by ondrolexa** [comment]
Do we need to specify minimal version numbers for `numpy` and `scipy` in `setup.py`?

**Comment by ondrolexa** [comment]
We should also reflect `pytest-runner` [deprecation](https://pypi.org/project/pytest-runner).

**Comment by uetoyo** [comment]
> We should also reflect `pytest-runner` [deprecation](https://pypi.org/project/pytest-runner).
Yes, we can (should) remove it.

> Do we need to specify minimal version numbers for NumPy and scipy in setup.py?
I don't know. But scipy project explicitly write NumPy minimal version: https://github.com/scipy/scipy/blob/master/setup.py

Maybe when we drop Python 2 support, it will be useful to keep the minimal version.

**Comment by uetoyo** [comment]
I want to leave a note about my current workflow with `setup.py` without conda.

__Create virtual environment in the project folder__

```
py -3.7 -m venv .venv
```

__Activate the virtual environment__

```
.venv\scripts\activate
```

__Install all dependencies__

```
pip install -e  ".[docs, test, lint]"
```

__Invoke pytest or black__

```
pytest tests
```
````
black src
````

**Comment by ondrolexa** [comment]
But `apsg` is part of [conda-forge](https://github.com/conda-forge/apsg-feedstock) ([repo](https://anaconda.org/conda-forge/apsg))so we have to follow their CI workflow as well.

**Comment by uetoyo** [comment]
> 
> 
> But `apsg` is part of [conda-forge](https://github.com/conda-forge/apsg-feedstock) ([repo](https://anaconda.org/conda-forge/apsg)) so we have to follow their CI workflow as well.

... should work. The `setup.py` and my development workflow is quite standard, isn't it?

**Comment by ondrolexa** [comment]
I suggest to include dropping Python 2.7 support in project structure change and include it in next point release.

**Comment by ondrolexa** [comment]
I suggest running Black with --skip-string-normalization, or -S for short option to allow not so strict subset of PEP 8  string quotes policies. I argue for that (except for docstrings, which should always be """ per PEP 257) as many people use quote style to convey meaning, with single quotes meaning "data" and double quotes meaning "human-readable string". To drop formatting commit would be appreciated.

**Pull request merged**
